### ISSUE TITLE
Failure if apticron is already installed

### ISSUE THREAD

**Issue by ntd** [kosssi/ansible-role-apticron#3]
Hi Simon,

I had a sever that failed with:

    fatal: [remotix]: FAILED! => {"changed": false, "failed": true, "gid": 0, "group": "root", "mode": "0755", "msg": "refusing to convert between file and link for /etc/cron.daily/apticron", "owner": "root", "path": "/etc/cron.daily/apticron", "size": 85, "state": "file", "uid": 0}

That server has `apticron` previously installed, hence `/etc/cron.daily/apticron` is already existent. Adding `force: yes` to the `file` item of the `Install apticron cron.file` task fixed the problem.

**Comment by kosssi** [comment]
hello @ntd 

Thanks for your report, can you create a PR ?

**Comment by ntd** [comment]
> Thanks for your report, can you create a PR ?

Of course. Done with pull #4.

**Comment by kosssi** [comment]
#v1.0.2 is for you.

**Comment by ntd** [comment]
Many thanks.
